version: '3'
services:
  telegram-bot:
    build: ./telegram-bot
    container_name: telegram-bot
    ports:
      - "3000:3000"
    depends_on:
      - tele-lb
    environment:
      - LOADBALANCER_URL=http://tele-lb:8080
      - TELEGRAM_BOT_TOKEN=8496833085:AAGz-GazNxgOLQowhd8BE4xdN2hdmJNiu5U

  tele-lb:
    build: ./tele-lb
    container_name: tele-lb
    ports:
      - "8080:8080"
    depends_on:
      - bot-telebackend1
      - bot-telebackend2
      - bot-telebackend3

  bot-telebackend1:
    build: ./bot-telebackend1
    container_name: bot-telebackend1
    environment:
      - PORT=3001
      - BOT_NAME=bot1
    ports:
      - "3001:3001"

  bot-telebackend2:
    build: ./bot-telebackend2
    container_name: bot-telebackend2
    environment:
      - PORT=3002
      - BOT_NAME=bot2
    ports:
      - "3002:3002"

  bot-telebackend3:
    build: ./bot-telebackend3
    container_name: bot-telebackend3
    environment:
      - PORT=3003
      - BOT_NAME=bot3
    ports:
      - "3003:3003"

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

volumes:
  ollama_data:
