version: '3'
services:
  baileys-bot:
    build: ./baileys-bot
    container_name: baileys-bot
    ports:
      - "3000:3000"
    depends_on:
      - whatsapp-lb
    environment:
      - LOADBALANCER_URL=http://whatsapp-lb:8080

  whatsapp-lb:
    build: ./whatsapp-lb
    container_name: whatsapp-lb
    ports:
      - "8080:8080"
    depends_on:
      - bot-backend1
      - bot-backend2
      - bot-backend3

  bot-backend1:
    build: ./bot-backend1
    container_name: bot-backend1
    environment:
      - PORT=3001
      - BOT_NAME=bot1
    ports:
      - "3001:3001"

  bot-backend2:
    build: ./bot-backend2
    container_name: bot-backend2
    environment:
      - PORT=3002
      - BOT_NAME=bot2
    ports:
      - "3002:3002"

  bot-backend3:
    build: ./bot-backend3
    container_name: bot-backend3
    environment:
      - PORT=3003
      - BOT_NAME=bot3
    ports:
      - "3003:3003"
